### ISSUE TITLE
Add custom wordpress posts

### ISSUE THREAD

**Issue by Abdou00** [philipehsing/jQuery.Simple-Event-Calendar#16]
Hello everybody,
I join the event calendar plugin jquery in my wordpress site and wanted to know if it was possible to recover my events (customs posts type), in the calendar?

**Comment by philipehsing** [comment]
Hey, yes ofc! You can load it with ajax or make an query in wp and loop all custom posts from post_type and to render the html

Which do you prefer? 
/ Philip

**Comment by Abdou00** [comment]
Thanks for you answer! I want to use wp_query, any idea? And how do I link my events with the calendar?

**Comment by philipehsing** [comment]
I had made a shortcode for the calendar html.
In shortcoden I had laid a wp_query to loop through all custom_posts and then created the html below as examples

<Div class = "day-event" date-month = "2" date-day = "16" date-year = "2016" data-number = "1">
<a href="#" class="close fontawesome-remove"> </a>
<H2 class = "title"> Lorem ipsum 3 </ h2>
<Span class = "date"> 2014-12-16 </ span>
<P> Lorem Ipsum is dummy text of the printing and publishing industry. Lorem Ipsum has been the standard since the 1500s, when an unknown boksättare took the number of type and scrambled it to make a sample copy of a book. </ P>
<Button class = "read-more"> Read more </ button>
</ Div>

**Comment by philipehsing** [comment]
I can help you do it, but then I need access to wp-admin, or you send a database dump and the theme

**Comment by Abdou00** [comment]
Thanks I'll apreciate that. I have a github: [https://github.com/PolesProd/PouvoirDAgir/tree/samba](url) 
[wordpress.sql.zip](https://github.com/philipehsing/jQuery.Simple-Event-Calendar/files/553429/wordpress.sql.zip)

**Comment by Abdou00** [comment]
My calendar is in page-test.php template.

**Comment by philipehsing** [comment]
Can i take a look at it later today? Busy at work atm :(

**Comment by Abdou00** [comment]
Of course! Thank you ;)

**Comment by philipehsing** [comment]
i need your username/password

**Comment by philipehsing** [comment]
can u add me on skype asap? philip.ehsing
